name: Basic sanity checks

on:
  workflow_call:
    inputs:
      head_ref:
        required: true
        type: string
      target_ref:
        required: true
        type: string
      commit_count:
        required: true
        type: number

permissions:
  contents: read

jobs:
  check:
    name: Check code formatting and build configuration
    runs-on: [self-hosted, ubuntu, asrunner]
    container:
      image: alpine:3.14

    steps:
    - name: pre
      run: |
        echo "nameserver 8.8.8.8" > /etc/resolv.conf
        apk add git python3 py3-pip clang-extra-tools shellcheck
        python3 -m pip install lint-diffs flake8

    - name: Checkout PR commits
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.head_ref }}
    - run: git fetch --depth $(( ${{ inputs.commit_count }} + 1 )) origin "${{ inputs.head_ref }}"

    - name: Check merge conditions
      run: |
        export "PATH=$PATH:/usr/share/clang"
        ./build_tools/spdb_merge_check.sh "${{ inputs.target_ref }}" "${{ inputs.head_ref }}"

    - name: Compare buckify output
      run: buckifier/check_buck_targets.sh

    - name: Simple source code checks
      run: build_tools/check-sources.sh
